#!/bin/bash
# Basic pre-commit script

EXIT_CODE=0

echo -e "\n\t************************************************\n\t*  Sensiolabs Security Checker *\n\t************************************************" ||
# Sensiolabs Security Checker
./vendor/bin/security-checker security:check --ansi || EXIT_CODE=1

# PHP Lint
./hooks/commands/parallel_lint.sh || EXIT_CODE=1

# PHPUnit
./hooks/commands/phpunit.sh || EXIT_CODE=1

# PHP CodeSniffer
#./hooks/commands/phpcs.sh || EXIT_CODE=1

# PHP Mess Detector
./hooks/commands/phpmd.sh || EXIT_CODE=1

[ $EXIT_CODE -ne 0 ] &&
echo -e "\n\t************************************************\n\t*  PRE-COMMIT HOOK FAILED (see reasons above)  *\n\t************************************************" ||
echo -e "\n\t*********************************************\n\t*  PRE-COMMIT HOOK PASSED, ready to commit  *\n\t*********************************************"

exit $EXIT_CODE